---
title: "Final Project Presentation"
author: "John Donnellan"
format: 
  revealjs:
    theme: "serif"
  
editor: visual
---

```{r}
library(tidyverse)
library(plotly)

sleep <- read_csv("data/Sleep_health_and_lifestyle_dataset.csv")|>
  rename(
    sleep_quality = `Quality of Sleep`,
    sleep_duration = `Sleep Duration`,
    physical_activity = `Physical Activity Level`,
    stress_level = `Stress Level`,
    bmi_category = `BMI Category`,
    sleep_disorder = `Sleep Disorder`,
    heart_rate = `Heart Rate`) |>
  select(-`Person ID`, -`Blood Pressure`, -`Daily Steps`)|>
  #Used Chat GPT to learn how to use fct_relevel and str_replace:
  #prompt: How can I adjust the response "Normal Weight" to "Normal"?
  mutate(bmi_category = str_replace(bmi_category,"Normal Weight", "Normal"),
         Occupation = str_replace(Occupation, "Sales Representative", "Salesperson"),
  #Prompt: How can I reorder facets and bars in my bar graph using factor?
         bmi_category = fct_relevel(bmi_category, "Normal", "Overweight","Obese"),
         sleep_disorder = fct_relevel(sleep_disorder, "None", "Insomnia", "Sleep Apnea")
  )
```

## Data Introduction

-   Data: Sleep Health and Lifestyle Dataset via Kaggle

    -   https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset

-   Variables:

    -   Demographic

        -   Age, Gender

    -   Sleep Metrics

        -   Sleep Duration, Quality of Sleep, Sleep Disorder

    -   Lifestyle

        -   Occupation, Stress Level, Physical Activity Level

    -   Health Indicators

        -   BMI Category, Heart Rate

## Sleep vs Stress by Occupation

```{r}
by_occupation <- sleep|>
  group_by(Occupation)|>
  summarise(
    n = n(),
    avg_sleep_hrs = mean(sleep_duration),
    avg_sleep_quality = mean(sleep_quality),
    avg_stress = mean(stress_level),
    avg_activity = mean(physical_activity))

sleep_vs_stress <- ggplot(data = by_occupation, 
                          aes(x = avg_sleep_hrs, 
                              y = avg_stress, 
                              label = Occupation, 
                              color = Occupation))+
  geom_point(size = 4) +
  geom_smooth(data = sleep, 
              aes(x = sleep_duration, 
                  y = stress_level, 
                  group = 1), 
              method = lm, 
              se = FALSE, 
              color = "grey90")+
  labs(
    title = "The Effects of Stress on Sleep by Occupation",
    x = "Average Sleep Duration",
    y = "Average Stress Level",
    caption = "Each point is an Occupation"
  ) +
  theme_minimal(base_size = 20)+
  theme(legend.position = "none")+
  scale_color_brewer(palette = "Paired")
  

ggplotly(sleep_vs_stress, tooltip = "label")
  
```

## Sleep Disorders
::: {.panel-tabset}
### General
```{r}
ggplot(data = sleep, 
       aes(x = sleep_disorder, 
           fill = sleep_disorder, 
           alpha = .7, 
           color = sleep_disorder))+
  geom_histogram(stat= "count")+
  facet_grid(~bmi_category)+
  theme_minimal()+
  theme(legend.position = "none")+
  labs(
    title = "Sleep Disorders by BMI Catagory",
    x = "Sleep Disorder",
    y = "Count")
```
### Occupational
```{r}
sleep |>
  ggplot(aes(x = sleep_disorder,
             fill = sleep_disorder,
             color = sleep_disorder)) +
  geom_bar(alpha = 0.7) +
  facet_wrap(~Occupation) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    title = "Sleep Disorders by Occupation",
    x = "Sleep Disorder",
    y = "Count"
  )
```
:::
## Shiny App

```{r}
library(shiny)
library(tidyverse)
library(glue)

#Strictly for appearance I asked chat GPT to help make all the variable names, title, and table labels cleaner. Definitely not necessary but I wanted it to look clean. petty_label will be used several times later in the code
pretty_label <- function(x) {
  str_replace_all(x, "_", " ") |> str_to_title()
}
occupation_choices <- unique(sleep$Occupation)

#Chat GPT helped me make the variables appear cleaner in the drop down
#Prompt: How can I rename my variable names in choices for my shiny app?
var_choices <- c(
  "Age"               = "Age",
  "Sleep Duration"    = "sleep_duration",
  "Sleep Quality"     = "sleep_quality",
  "Physical Activity" = "physical_activity",
  "Stress Level"      = "stress_level",
  "Heart Rate"        = "heart_rate"
)

ui <- fluidPage(
   sidebarLayout(
    sidebarPanel(
      #Chat GPT helped me learn how to create multiple selection input
      #Prompt: Is there an option to allow for multiple boxes to be selected in my shiny sidebarpanel?
      checkboxGroupInput(
        "occupation_choose",
        label = "Select Occupation(s):",
        choices = occupation_choices,
        selected = c("Lawyer", 
                     "Software Engineer", 
                     "Doctor","Teacher", 
                     "Nurse", 
                     "Engineer", 
                     "Salesperson", 
                     "Manager", 
                     "Scientist",
                     "Accountant")),
      
      selectInput("xaxis_choose",
                  label = "Choose X-Axis Variable:",
                  choices = var_choices,
                  selected = "Age"),
      
      selectInput("yaxis_choose",
                  label = "Choose Y-Axis Variable:",
                  choices = var_choices,
                  selected = "sleep_duration")),
    
    mainPanel(
      plotOutput("final_plot"),
      plotOutput("second_plot"),
      tableOutput("final_table")
      
    )
  )
)

server <- function(input, output, session) {
  
  plot_sleep <- reactive({
    sleep |> filter(Occupation %in% input$occupation_choose)
  })
  
  output$final_plot <- renderPlot({
    ggplot(plot_sleep(),
           aes(x = .data[[input$xaxis_choose]],
               y = .data[[input$yaxis_choose]],
               color = Occupation)) +
      geom_point(size = 2) +
      #Used Chat GPT to create a geom_smooth for complete data
      #Prompt: How can I create a single geom_smooth for my data that is currently grouped by color?
      geom_smooth(aes(group = 1), 
                  method = lm, 
                  se = FALSE, 
                  color = "grey90")+
      theme_minimal(base_size = 15) +
      labs(
        #Used Chat GPT to learn how to use pretty_label function to clean up the titles on graph
        # Prompt: Is there a function to clean up my labels on graphs and tables and how do I use it? Give me an example for "Title = glue::glue("Scatterplot of [[input$yaxis_choose]] vs [[input$xaxis_choose]]"
        title = glue("Scatterplot of {pretty_label(input$yaxis_choose)} vs {pretty_label(input$xaxis_choose)}"),
        x = pretty_label(input$xaxis_choose),
        y = pretty_label(input$yaxis_choose),
        color = "Occupation")+
      scale_color_brewer(palette = "Paired")
  })
  
  output$second_plot <- renderPlot({
    ggplot(plot_sleep(),
           aes(x = sleep_disorder,
               fill = sleep_disorder)) +
      geom_histogram(stat= "count")+
      theme_minimal(base_size = 15)+
      theme(legend.position = "none")+
      labs(
        title = "Sleep Disorders by Occupation",
        x = "Sleep Disorder",
        y = "Count")
  })
  
  output$final_table <- renderTable({
    plot_sleep() |>
      group_by(Occupation) |>
      summarise(
        #Used Chat GPT to clean up table column names
        #Prompt: How can I use pretty label and glue package to clean up these table names/labels:
        #Max_Y = max(.data[[input$yaxis_choose]], 
        #Mean_Y = mean(.data[[input$yaxis_choose]]), 
        #Min_Y = min(.data[[input$yaxis_choose]]), 
        #Max_X = max(.data[[input$xaxis_choose]], 
        #Mean_X = mean(.data[[input$xaxis_choose]]), 
        #Min_X = mean(.data[[input$xaxis_choose]]))
        N = n(),
        !!glue("Min {pretty_label(input$yaxis_choose)}")  := min(.data[[input$yaxis_choose]]),
        !!glue("Mean {pretty_label(input$yaxis_choose)}") := mean(.data[[input$yaxis_choose]]),
        !!glue("Max {pretty_label(input$yaxis_choose)}")  := max(.data[[input$yaxis_choose]]),
        !!glue("Min {pretty_label(input$xaxis_choose)}")  := min(.data[[input$xaxis_choose]]),
        !!glue("Mean {pretty_label(input$xaxis_choose)}") := mean(.data[[input$xaxis_choose]]),
        !!glue("Max {pretty_label(input$xaxis_choose)}")  := max(.data[[input$xaxis_choose]]))
  })
}

shinyApp(ui, server)
```
